name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Lint du code
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Linting
        run: npm run lint

  unit-test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Tests unitaires
        run: npm test

  integration-test:
    name: Tests d'intégration
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Tests d'intégration
        run: echo "Hello Integration !"

  e2e-test:
    name: Tests E2E
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.event_name == 'pull_request'
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Tests E2E
        run: echo "Hello E2E !"

  canary-deploy:
    name: Déploiement Canary
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      vars.ENV_TARGET == 'canary'
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Déploiement Canary
        run: echo "Hello Only Canary !"

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration Git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --yes release-it --ci